name: CI/CD

on:
  push:
    branches: [master]
    paths:
      - "client/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: cd client && npm install

      - name: Run the tests
        run: cd client && npm test

      - name: Build
        run: cd client && npm run build

      - name: Add frontend remote origin
        run: git remote add waqas-qa https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy frontend to Heroku on master
        run: git push waqas-qa `git subtree split --prefix frontend master`:refs/heads/master --force
